// Templates will be like pages: home, about, etc
export { default as PageOne } from './pageOne/pageOne.jsx'
export { default as PageTwo } from './pageTwo/pageTwo.jsx'
export { default as Login } from './login/login.jsx'
// export { default as Checkin } from './checkin/checkin.jsx'
export { default as Reservations } from './carReservations/reservations.jsx'
export { default as AdressData } from './userAddressData/addressData'
export { default as UserVerification } from './userVerification/userVerification'
export { default as Deposit } from './userDeposit/deposit.jsx'
export { default as QR } from './receivedQR/qr.jsx'
