// A atom will be a specific part, such as button, heading 1, input field, etc.
export { default as HeadingOne } from './headingOne/headingOne.jsx'
export { default as EditButton } from './editButton/editButton.jsx'
// export { default as CameraIcon } from './_icons/cameraIcon/cameraIcon.jsx'
export { default as InlineButton } from './inlineButton/inlineButton.jsx'
export { default as Label } from './label/label.jsx'
export { default as TextInput } from './textInput/textInput.jsx'
export { default as PasswordInput } from './passwordInput/passwordInput.jsx'
export { default as FormButtonPrimaryLarge } from './formButtonPrimaryLarge/formButtonPrimaryLarge.jsx'
export { default as Icons } from './icons/icons.jsx'
export { default as ButtonPrimary } from './buttonPrimary/buttonPrimary.jsx'
export { default as ButtonSecondary } from './buttonSecondary/buttonSecondary.jsx'
export { default as ButtonTertiary } from './buttonTertiary/buttonTertiary.jsx'
